// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageWrapper.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MessageWrapper.proto</summary>
public static partial class MessageWrapperReflection {

  #region Descriptor
  /// <summary>File descriptor for MessageWrapper.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageWrapperReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRNZXNzYWdlV3JhcHBlci5wcm90bxoNTWVzc2FnZS5wcm90byJlCg5NZXNz",
          "YWdlV3JhcHBlchIWCg5zZXJ2ZXJJbnN0YW5jZRgBIAEoCRIQCghwbGF5ZXJJ",
          "ZBgCIAEoAxIOCgZ1c2VySWQYAyABKAMSGQoHbWVzc2FnZRgEIAEoCzIILk1l",
          "c3NhZ2ViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MessageReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MessageWrapper), global::MessageWrapper.Parser, new[]{ "ServerInstance", "PlayerId", "UserId", "Message" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class MessageWrapper : pb::IMessage<MessageWrapper>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MessageWrapper> _parser = new pb::MessageParser<MessageWrapper>(() => new MessageWrapper());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MessageWrapper> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageWrapperReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MessageWrapper() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MessageWrapper(MessageWrapper other) : this() {
    serverInstance_ = other.serverInstance_;
    playerId_ = other.playerId_;
    userId_ = other.userId_;
    message_ = other.message_ != null ? other.message_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MessageWrapper Clone() {
    return new MessageWrapper(this);
  }

  /// <summary>Field number for the "serverInstance" field.</summary>
  public const int ServerInstanceFieldNumber = 1;
  private string serverInstance_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ServerInstance {
    get { return serverInstance_; }
    set {
      serverInstance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "playerId" field.</summary>
  public const int PlayerIdFieldNumber = 2;
  private long playerId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PlayerId {
    get { return playerId_; }
    set {
      playerId_ = value;
    }
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 3;
  private long userId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 4;
  private global::Message message_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Message Message {
    get { return message_; }
    set {
      message_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MessageWrapper);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MessageWrapper other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServerInstance != other.ServerInstance) return false;
    if (PlayerId != other.PlayerId) return false;
    if (UserId != other.UserId) return false;
    if (!object.Equals(Message, other.Message)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ServerInstance.Length != 0) hash ^= ServerInstance.GetHashCode();
    if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
    if (UserId != 0L) hash ^= UserId.GetHashCode();
    if (message_ != null) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ServerInstance.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ServerInstance);
    }
    if (PlayerId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(PlayerId);
    }
    if (UserId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(UserId);
    }
    if (message_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ServerInstance.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ServerInstance);
    }
    if (PlayerId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(PlayerId);
    }
    if (UserId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(UserId);
    }
    if (message_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ServerInstance.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerInstance);
    }
    if (PlayerId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
    }
    if (UserId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
    }
    if (message_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MessageWrapper other) {
    if (other == null) {
      return;
    }
    if (other.ServerInstance.Length != 0) {
      ServerInstance = other.ServerInstance;
    }
    if (other.PlayerId != 0L) {
      PlayerId = other.PlayerId;
    }
    if (other.UserId != 0L) {
      UserId = other.UserId;
    }
    if (other.message_ != null) {
      if (message_ == null) {
        Message = new global::Message();
      }
      Message.MergeFrom(other.Message);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ServerInstance = input.ReadString();
          break;
        }
        case 16: {
          PlayerId = input.ReadInt64();
          break;
        }
        case 24: {
          UserId = input.ReadInt64();
          break;
        }
        case 34: {
          if (message_ == null) {
            Message = new global::Message();
          }
          input.ReadMessage(Message);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ServerInstance = input.ReadString();
          break;
        }
        case 16: {
          PlayerId = input.ReadInt64();
          break;
        }
        case 24: {
          UserId = input.ReadInt64();
          break;
        }
        case 34: {
          if (message_ == null) {
            Message = new global::Message();
          }
          input.ReadMessage(Message);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
